      
import colorama
from tiempo import sleep, sleep3
from gatos import gato
from colores import amarillo, rosa, blanco, verde
colorama.init()
def suma():
              print(amarillo + "¡Muy bien! Entonces vas a sumar. ¿Qué número deseas sumar?" + gato[5])
              sleep()
              Valor1 = int(input(""))
              sleep()
              Valor2 = int(input(f"¡Perfecto! Entonces será {Valor1}" + gato[6]))
              sleep(3)
              print(rosa + "Y entonces el resultado es...." + blanco + "*(redoble de tambores de suspenso)*")
              sleep3()
              print(verde + "¡" + Valor1 + Valor2 + "!" + gato[8])
def resta():
              print(amarillo + "¡Muy bien! Entonces vas a restar. ¿Qué número deseas restar?" + gato[5])
              sleep()
              Valor1 = int(input(""))
              sleep()
              Valor2 = int(input(f"¡Perfecto! Entonces será {Valor1}" + gato[6]))
              sleep(3)
              print(rosa + "Y entonces el resultado es...." + blanco + "*(redoble de tambores de suspenso)*")
              sleep3()
              print(verde + "¡" + Valor1 - Valor2 + "!" + gato[8])
def multiplicar():
              print(amarillo + "¡Muy bien! Entonces vas a multiplicar. ¿Qué número deseas multiplicar?" + gato[5])
              sleep()()
              Valor1 = int(input(""))
              sleep()()
              Valor2 = int(input(f"¡Perfecto! Entonces será {Valor1}" + gato[6]))
              sleep()(3)
              print(rosa + "Y entonces el resultado es...." + blanco + "*(redoble de tambores de suspenso)*")
              sleep3()
              print(verde + "¡" + Valor1 * Valor2 + "!" + gato[8])
def dividir():
              print(amarillo + "¡Muy bien! Entonces vas a dividir. ¿Qué número deseas dividir?")
              sleep()()
              Valor1 = int(input(""))
              sleep()()
              Valor2 = int(input(f"¡Perfecto! Entonces será {Valor1}" + gato[6]))
              sleep()(3)
              print(rosa + "Y entonces el resultado es...." + blanco + "*(redoble de tambores de suspenso)*")
              sleep3()
              print(verde + "¡" + Valor1 / Valor2 + "!" + gato[8])
def dividir_entero():
              print(amarillo + "¡Muy bien! ¡Entonces vas a hacer una división entera!. ¿Qué número deseas dividir?" + gato[5])
              sleep()()
              Valor1 = int(input(""))
              sleep()()
              Valor2 = int(input(f"¡Perfecto! Entonces será {Valor1}" + gato[6]))
              sleep()(3)
              print(rosa + "Y entonces el resultado es...." + blanco + "*(redoble de tambores de suspenso)*")
              sleep3()
              print(verde + "¡" + Valor1 // Valor2 + "!" + gato[8])
def exponente():
              print(amarillo + "¡Muy bien! Entonces vas a  Exponente. ¿Qué número deseas elevar?" + gato[5])
              sleep()()
              Valor1 = int(input(""))
              sleep()()
              Valor2 = int(input(f"¡Perfecto! Entonces será {Valor1} ¿Por cuál número deseas elevarlo?" + gato[6]))
              sleep()(3)
              print(rosa + "Y entonces el resultado es...." + blanco + "*(redoble de tambores de suspenso)*")
              sleep3()
              print(verde + "¡" + Valor1 ** Valor2 + "!" + gato[8])